sudo: required

services:
  - docker

language: java
jdk: 
  - oraclejdk8

before_install:
  - docker build -t quay.io/collaboratoryicy-blackberry:1.0 .
  - pip2.7 install --user setuptools==24.0.3

install: 
  - pip2.7 install --user cwl-runner cwltool==1.0.20160712154127 schema-salad==1.14.20160708181155 avro==1.8.1
  - wget https://github.com/broadinstitute/cromwell/releases/download/28.2/cromwell-28_2.jar

script: 
  - cwltool --non-strict Dockstore.cwl params.cwl.local.json
  - java -jar cromwell-28_2.jar run Dockstore.wdl params.wdl.json
